### ISSUE TITLE
[Suggestion] Merge Nest.js into master

### ISSUE THREAD

**Issue by szymski** [Bartekkur1/janpa-js#1]
Hi! I looked through the documentation of JanpaJS and realized it does exactly what Nest.js does, therefore I suggest giving up on current state and merging Nest.js into master (or main, see #2). This way we get exactly the same functionality we have in JanpaJS currently + much more battle-tested features, covered in unit tests.
Link to Nest.js: https://github.com/nestjs/nest

**Comment by Bartekkur1** [comment]
Hi @szymski just 5 minutes ago I didn't even know that nestjs existed. I'm glad that someone has similar ideas to mine or I have similar to someone's ideas. 
Of course I won't merge Nest.js to master because this project is my playground for testing and developing ideas. If you want a _battle-tested features_ and high test coverage **I DO NOT RECOMMEND** using this project but if you want to have fun with typescript or test some of your own ideas here, you are welcome.
